/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kuNDIWrapperTest_KuNDIWrapper */

#ifndef _Included_kuNDIWrapperTest_KuNDIWrapper
#define _Included_kuNDIWrapperTest_KuNDIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuWrapperHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuWrapperHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuWrapperAddTest
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuWrapperAddTest
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuStartNDI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuStartNDI
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnCnt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnCnt
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnProtocolFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnProtocolFlag
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnPolarisFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnPolarisFlag
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnToolsFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnToolsFlag
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnXmlLoadFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnXmlLoadFlag
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnProtocolCheckFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnProtocolCheckFlag
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnInitFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnInitFlag
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnStartFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnStartFlag
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnDataFailFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnDataFailFlag
  (JNIEnv *, jobject);

/*
 * Class:     kuNDIWrapperTest_KuNDIWrapper
 * Method:    kuReturnLoadFailFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kuNDIWrapperTest_KuNDIWrapper_kuReturnLoadFailFlag
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
